In [ ]:
import os
import re
import sys
import json
import time
import shutil
import hashlib
import asyncio
import inspect
import getpass
import subprocess
import importlib
import importlib.metadata
from pathlib import Path
from typing import List, Dict, Any

def run_shell(cmd, check=True):
    print(f"\n$ {cmd}")
    result = subprocess.run(cmd, shell=True, text=True)
    if check and result.returncode != 0:
        raise RuntimeError(f"Command failed: {cmd}")
    return result.returncode

print("=" * 80)
print("RAG-Anything Advanced Colab Tutorial")
print("=" * 80)

print("\n[1/10] Installing dependencies...")

for module_name in list(sys.modules):
    if module_name == "PIL" or module_name.startswith("PIL."):
        del sys.modules[module_name]

run_shell(
    'pip -q install -U '
    '"raganything[image,text]" '
    '"openai>=1.0.0" '
    '"python-dotenv" '
    '"reportlab" '
    '"pandas" '
    '"matplotlib" '
    '"tabulate"'
)

run_shell('pip -q install --no-cache-dir --force-reinstall "pillow==11.3.0"')

for module_name in list(sys.modules):
    if module_name == "PIL" or module_name.startswith("PIL."):
        del sys.modules[module_name]

importlib.invalidate_caches()

try:
    print("Pillow version:", importlib.metadata.version("Pillow"))
except Exception as e:
    print("Could not read Pillow version:", repr(e))

print("\n[2/10] Importing libraries...")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from IPython.display import display
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch

from openai import AsyncOpenAI
from raganything import RAGAnything, RAGAnythingConfig
from lightrag.utils import EmbeddingFunc

print("Imports successful.")

In [ ]:
print("\n[3/10] Preparing directories and runtime settings...")

BASE_DIR = Path("/content/raganything_advanced_tutorial") if Path("/content").exists() else Path.cwd() / "raganything_advanced_tutorial"
ASSET_DIR = BASE_DIR / "assets"
OUTPUT_DIR = BASE_DIR / "output"
WORKING_DIR = BASE_DIR / "rag_storage"
LOG_DIR = BASE_DIR / "logs"

RESET_STORAGE = True

RUN_FULL_DOCUMENT_PARSE = False
PARSER_FOR_FULL_PARSE = "mineru"
PARSE_METHOD = "auto"

for d in [BASE_DIR, ASSET_DIR, OUTPUT_DIR, WORKING_DIR, LOG_DIR]:
    d.mkdir(parents=True, exist_ok=True)

if RESET_STORAGE and WORKING_DIR.exists():
    shutil.rmtree(WORKING_DIR)
    WORKING_DIR.mkdir(parents=True, exist_ok=True)

os.environ["LOG_DIR"] = str(LOG_DIR)
os.environ["SUMMARY_LANGUAGE"] = "English"
os.environ["ENABLE_LLM_CACHE"] = "false"
os.environ["ENABLE_LLM_CACHE_FOR_EXTRACT"] = "false"
os.environ["MAX_ASYNC"] = "2"
os.environ["CHUNK_SIZE"] = "900"
os.environ["CHUNK_OVERLAP_SIZE"] = "120"
os.environ["TIMEOUT"] = "240"

for var in [
    "OPENAI_API_KEY",
    "OPENAI_ORG_ID",
    "OPENAI_ORGANIZATION",
    "OPENAI_PROJECT",
    "OPENAI_DEFAULT_HEADERS",
    "LLM_BINDING_API_KEY",
    "LLM_BINDING_HOST",
]:
    os.environ.pop(var, None)

print(f"Base directory: {BASE_DIR}")
print(f"Assets directory: {ASSET_DIR}")
print(f"Storage directory: {WORKING_DIR}")

print("\n[4/10] Entering OpenAI API key securely...")

def clean_api_key(raw_value: str) -> str:
    raw_value = str(raw_value or "").strip()

    raw_value = raw_value.replace("Bearer ", "").replace("bearer ", "").strip()
    raw_value = raw_value.strip("'").strip('"').strip("`").strip()

    if "=" in raw_value:
        raw_value = raw_value.split("=", 1)[1].strip().strip("'").strip('"').strip("`")

    raw_value = re.sub(r"\s+", "", raw_value)
    raw_value = raw_value.encode("ascii", errors="ignore").decode("ascii").strip()

    return raw_value

OPENAI_API_KEY_RAW = getpass.getpass("Paste your OpenAI API key here. Input is hidden: ")
OPENAI_API_KEY = clean_api_key(OPENAI_API_KEY_RAW)

if not OPENAI_API_KEY:
    raise ValueError(
        "No API key was captured. Paste the key into the hidden input box and press Enter."
    )

print("Captured key length:", len(OPENAI_API_KEY))
print("Captured key prefix:", OPENAI_API_KEY[:12] + "...")
print("Captured key suffix:", "..." + OPENAI_API_KEY[-6:])

LLM_MODEL = "gpt-4o-mini"
VISION_MODEL = "gpt-4o-mini"
EMBEDDING_MODEL = "text-embedding-3-small"
EMBEDDING_DIM = 1536

openai_client = AsyncOpenAI(api_key=OPENAI_API_KEY)

os.environ["LLM_MODEL"] = LLM_MODEL
os.environ["VISION_MODEL"] = VISION_MODEL
os.environ["EMBEDDING_MODEL"] = EMBEDDING_MODEL
os.environ["EMBEDDING_DIM"] = str(EMBEDDING_DIM)

print("Testing OpenAI chat API with the captured key...")

try:
    test_response = await openai_client.chat.completions.create(
        model=LLM_MODEL,
        messages=[{"role": "user", "content": "Reply with exactly: ok"}],
        temperature=0,
    )
    print("Chat API test response:", test_response.choices[0].message.content)
except Exception as e:
    raise RuntimeError(
        "The key was captured, but OpenAI rejected the request or the account/model access failed. "
        "Check billing, project permissions, and make sure this is an OpenAI Platform API key."
    ) from e

print("\nTesting OpenAI embedding API...")

try:
    test_embedding = await openai_client.embeddings.create(
        model=EMBEDDING_MODEL,
        input=["RAG-Anything embedding test"],
    )
    print("Embedding vector length:", len(test_embedding.data[0].embedding))
except Exception as e:
    raise RuntimeError(
        "Chat worked, but embeddings failed. Make sure your API key has permission for embeddings."
    ) from e

print("OpenAI API key is working.")
print(f"Chat model: {LLM_MODEL}")
print(f"Vision model: {VISION_MODEL}")
print(f"Embedding model: {EMBEDDING_MODEL}")
print(f"Embedding dimension: {EMBEDDING_DIM}")

In [ ]:
print("\n[5/10] Creating a synthetic multimodal report...")

monthly_data = pd.DataFrame(
    {
        "Month": ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
        "Query Volume": [1200, 1700, 2100, 2600, 3300, 4100],
        "Hybrid Accuracy": [0.71, 0.74, 0.79, 0.83, 0.87, 0.91],
        "Average Latency ms": [980, 920, 850, 790, 760, 730],
    }
)

table_md = monthly_data.to_markdown(index=False)

plt.figure(figsize=(8, 4.8))
plt.plot(monthly_data["Month"], monthly_data["Query Volume"], marker="o", label="Query Volume")
plt.plot(monthly_data["Month"], monthly_data["Hybrid Accuracy"] * 4000, marker="s", label="Hybrid Accuracy scaled")
plt.title("Multimodal RAG Usage and Quality Trend")
plt.xlabel("Month")
plt.ylabel("Volume / Scaled Accuracy")
plt.legend()
plt.grid(True, alpha=0.3)
plt.text(
    0.02,
    0.95,
    "Synthetic figure: usage rises while latency falls",
    transform=plt.gca().transAxes,
    fontsize=9,
    verticalalignment="top",
    bbox=dict(boxstyle="round", alpha=0.15),
)

chart_path = ASSET_DIR / "raganything_quality_trend.png"
plt.tight_layout()
plt.savefig(chart_path, dpi=180)
plt.close()

report_pdf_path = ASSET_DIR / "synthetic_multimodal_rag_report.pdf"

c = canvas.Canvas(str(report_pdf_path), pagesize=letter)
width, height = letter

c.setFont("Helvetica-Bold", 18)
c.drawString(0.8 * inch, height - 0.8 * inch, "Synthetic Multimodal RAG Evaluation Report")

c.setFont("Helvetica", 10)
intro_lines = [
    "This report evaluates a synthetic multimodal RAG pipeline for enterprise documents.",
    "The knowledge base includes text, tables, equations, and visual evidence.",
    "The central hypothesis is that hybrid retrieval improves answer quality when evidence spans modalities.",
]

y = height - 1.25 * inch
for line in intro_lines:
    c.drawString(0.8 * inch, y, line)
    y -= 0.22 * inch

c.setFont("Helvetica-Bold", 12)
c.drawString(0.8 * inch, y - 0.1 * inch, "Table 1. Monthly system measurements")
y -= 0.4 * inch

c.setFont("Courier", 7.5)
for row in table_md.splitlines():
    c.drawString(0.8 * inch, y, row[:120])
    y -= 0.17 * inch

c.setFont("Helvetica-Bold", 12)
c.drawString(0.8 * inch, y - 0.15 * inch, "Equation 1. Weighted multimodal score")
y -= 0.45 * inch

c.setFont("Helvetica", 9)
c.drawString(
    0.8 * inch,
    y,
    "Score(q, d) = alpha * Sim_text(q, d) + beta * Sim_graph(q, d) + gamma * Sim_visual(q, d)",
)
y -= 0.5 * inch

c.drawImage(str(chart_path), 0.8 * inch, y - 2.8 * inch, width=6.5 * inch, height=2.6 * inch)
c.showPage()

c.setFont("Helvetica-Bold", 16)
c.drawString(0.8 * inch, height - 0.8 * inch, "Interpretation and Findings")

c.setFont("Helvetica", 10)
findings = [
    "Hybrid retrieval combines semantic similarity with graph-based relationship navigation.",
    "The synthetic table shows accuracy improving from 0.71 to 0.91 over six months.",
    "The generated figure shows query volume increasing while latency gradually decreases.",
    "Equation-level retrieval is useful when the question depends on scoring logic rather than plain prose.",
    "A multimodal system should preserve page index, captions, footnotes, and local image paths for traceability.",
]

y = height - 1.25 * inch
for finding in findings:
    c.drawString(0.8 * inch, y, "- " + finding)
    y -= 0.28 * inch

c.save()

print(f"Created chart: {chart_path}")
print(f"Created PDF: {report_pdf_path}")

print("\nSynthetic table:")
display(monthly_data)

In [ ]:
print("\n[6/10] Building direct multimodal content_list...")

content_list: List[Dict[str, Any]] = [
    {
        "type": "text",
        "text": (
            "This synthetic report evaluates a multimodal retrieval augmented generation system. "
            "The system indexes textual explanations, a structured performance table, a scoring equation, "
            "and a trend figure. The main goal is to answer questions whose evidence is distributed across "
            "several document modalities rather than one plain text passage."
        ),
        "page_idx": 0,
    },
    {
        "type": "table",
        "table_body": table_md,
        "table_caption": ["Table 1: Monthly query volume, hybrid accuracy, and average latency."],
        "table_footnote": ["Synthetic measurements created for a Colab tutorial."],
        "page_idx": 0,
    },
    {
        "type": "equation",
        "latex": r"Score(q,d)=\alpha \cdot Sim_{text}(q,d)+\beta \cdot Sim_{graph}(q,d)+\gamma \cdot Sim_{visual}(q,d)",
        "text": (
            "Weighted multimodal retrieval score. Alpha controls text similarity, beta controls graph relationship "
            "similarity, and gamma controls visual similarity."
        ),
        "page_idx": 0,
    },
    {
        "type": "image",
        "img_path": str(chart_path.resolve()),
        "image_caption": ["Figure 1: Multimodal RAG usage and quality trend."],
        "image_footnote": ["The line chart is synthetic and generated inside this tutorial."],
        "page_idx": 0,
    },
    {
        "type": "text",
        "text": (
            "The key finding is that hybrid retrieval is preferred for cross-modal questions. "
            "Local retrieval is useful for entity-specific lookup, global retrieval is useful for broader themes, "
            "and naive retrieval is a simpler baseline. In this report, hybrid accuracy rises from 0.71 in January "
            "to 0.91 in June, while average latency drops from 980 milliseconds to 730 milliseconds."
        ),
        "page_idx": 1,
    },
]

content_list_path = ASSET_DIR / "content_list.json"
with open(content_list_path, "w", encoding="utf-8") as f:
    json.dump(content_list, f, indent=2, ensure_ascii=False)

print(f"Saved content list: {content_list_path}")

In [ ]:
print("\n[7/10] Defining clean OpenAI model and embedding functions...")

async def llm_model_func(prompt, system_prompt=None, history_messages=None, **kwargs):
    messages = []

    if system_prompt:
        messages.append({"role": "system", "content": str(system_prompt)})

    for msg in history_messages or []:
        if isinstance(msg, dict) and "role" in msg and "content" in msg:
            messages.append(msg)

    messages.append({"role": "user", "content": str(prompt)})

    allowed_kwargs = {}

    for key in ["temperature", "top_p", "max_tokens", "response_format"]:
        if key in kwargs and kwargs[key] is not None:
            allowed_kwargs[key] = kwargs[key]

    response = await openai_client.chat.completions.create(
        model=LLM_MODEL,
        messages=messages,
        **allowed_kwargs,
    )

    return response.choices[0].message.content or ""

async def vision_model_func(
    prompt,
    system_prompt=None,
    history_messages=None,
    image_data=None,
    messages=None,
    **kwargs,
):
    allowed_kwargs = {}

    for key in ["temperature", "top_p", "max_tokens", "response_format"]:
        if key in kwargs and kwargs[key] is not None:
            allowed_kwargs[key] = kwargs[key]

    if messages:
        clean_messages = [m for m in messages if m is not None]

        response = await openai_client.chat.completions.create(
            model=VISION_MODEL,
            messages=clean_messages,
            **allowed_kwargs,
        )

        return response.choices[0].message.content or ""

    built_messages = []

    if system_prompt:
        built_messages.append({"role": "system", "content": str(system_prompt)})

    for msg in history_messages or []:
        if isinstance(msg, dict) and "role" in msg and "content" in msg:
            built_messages.append(msg)

    if image_data:
        built_messages.append(
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": str(prompt)},
                    {
                        "type": "image_url",
                        "image_url": {"url": f"data:image/jpeg;base64,{image_data}"},
                    },
                ],
            }
        )
    else:
        built_messages.append({"role": "user", "content": str(prompt)})

    response = await openai_client.chat.completions.create(
        model=VISION_MODEL,
        messages=built_messages,
        **allowed_kwargs,
    )

    return response.choices[0].message.content or ""

async def openai_embedding_func(texts, **kwargs):
    if isinstance(texts, str):
        texts = [texts]

    texts = [str(t) for t in texts]

    response = await openai_client.embeddings.create(
        model=EMBEDDING_MODEL,
        input=texts,
    )

    vectors = [item.embedding for item in response.data]
    return np.array(vectors, dtype=np.float32)

embedding_func = EmbeddingFunc(
    embedding_dim=EMBEDDING_DIM,
    max_token_size=8192,
    func=openai_embedding_func,
)

print("Model and embedding functions ready.")

In [ ]:
print("\n[8/10] Initializing RAG-Anything...")

config = RAGAnythingConfig(
    working_dir=str(WORKING_DIR),
    parser=PARSER_FOR_FULL_PARSE,
    parse_method=PARSE_METHOD,
    enable_image_processing=True,
    enable_table_processing=True,
    enable_equation_processing=True,
)

rag = RAGAnything(
    config=config,
    llm_model_func=llm_model_func,
    vision_model_func=vision_model_func,
    embedding_func=embedding_func,
)

async def maybe_await(value):
    if inspect.isawaitable(value):
        return await value
    return value

if hasattr(rag, "initialize_storages"):
    try:
        await maybe_await(rag.initialize_storages())
        print("RAG-Anything storages initialized.")
    except Exception as e:
        print("Storage initialization skipped or already handled:", repr(e))

print(f"Working directory: {WORKING_DIR}")

print("\n[9/10] Inserting multimodal content and running retrieval queries...")

async def insert_demo_content():
    await rag.insert_content_list(
        content_list=content_list,
        file_path=str(report_pdf_path.name),
        split_by_character=None,
        split_by_character_only=False,
        doc_id="synthetic-multimodal-rag-report",
        display_stats=True,
    )

await insert_demo_content()
print("Insertion complete.")

queries = [
    "What is the main purpose of the multimodal RAG report?",
    "How did hybrid accuracy and latency change from January to June?",
    "Why is hybrid retrieval better than naive retrieval for this report?",
    "What does the weighted multimodal score equation mean?",
]

async def safe_aquery(question, mode="hybrid", vlm_enhanced=False):
    try:
        return await rag.aquery(question, mode=mode, vlm_enhanced=vlm_enhanced)
    except TypeError:
        return await rag.aquery(question, mode=mode)

async def run_query_suite():
    results = []

    for mode in ["naive", "local", "global", "hybrid"]:
        print("\n" + "=" * 80)
        print(f"QUERY MODE: {mode.upper()}")
        print("=" * 80)

        for q in queries:
            print(f"\nQuestion: {q}")

            try:
                answer = await safe_aquery(q, mode=mode, vlm_enhanced=False)
            except Exception as e:
                answer = f"Query failed in mode={mode}: {repr(e)}"

            print("\nAnswer:")
            print(answer)
            print("-" * 80)

            results.append(
                {
                    "mode": mode,
                    "question": q,
                    "answer_preview": str(answer)[:700],
                }
            )

    return pd.DataFrame(results)

query_results_df = await run_query_suite()

print("\nQuery result preview:")
display(query_results_df)

In [1]:
print("\n[10/10] Running explicit multimodal queries...")

async def run_multimodal_queries():
    multimodal_cases = [
        {
            "name": "Table-aware query",
            "question": (
                "Using the supplied table, identify the month with the highest hybrid accuracy, "
                "the month with the lowest latency, and explain whether the trend supports the report conclusion."
            ),
            "multimodal_content": [
                {
                    "type": "table",
                    "table_data": table_md,
                    "table_caption": "Monthly performance table",
                }
            ],
        },
        {
            "name": "Equation-aware query",
            "question": (
                "Explain how this scoring equation should affect retrieval when the user's question needs "
                "textual, graph, and visual evidence at the same time."
            ),
            "multimodal_content": [
                {
                    "type": "equation",
                    "latex": r"Score(q,d)=\alpha Sim_{text}(q,d)+\beta Sim_{graph}(q,d)+\gamma Sim_{visual}(q,d)",
                    "equation_caption": "Weighted multimodal retrieval score",
                }
            ],
        },
        {
            "name": "Combined multimodal query",
            "question": (
                "Connect the table, equation, and document conclusion into one explanation of why a multimodal "
                "hybrid retriever is useful."
            ),
            "multimodal_content": [
                {
                    "type": "table",
                    "table_data": table_md,
                    "table_caption": "Monthly performance table",
                },
                {
                    "type": "equation",
                    "latex": r"Score(q,d)=\alpha Sim_{text}(q,d)+\beta Sim_{graph}(q,d)+\gamma Sim_{visual}(q,d)",
                    "equation_caption": "Weighted multimodal retrieval score",
                },
            ],
        },
    ]

    outputs = []

    for case in multimodal_cases:
        print("\n" + "=" * 80)
        print(case["name"])
        print("=" * 80)
        print("Question:", case["question"])

        try:
            answer = await rag.aquery_with_multimodal(
                case["question"],
                multimodal_content=case["multimodal_content"],
                mode="hybrid",
            )
        except Exception as e:
            answer = f"Multimodal query failed: {repr(e)}"

        print("\nAnswer:")
        print(answer)

        outputs.append(
            {
                "case": case["name"],
                "question": case["question"],
                "answer_preview": str(answer)[:900],
            }
        )

    return pd.DataFrame(outputs)

multimodal_results_df = await run_multimodal_queries()

print("\nMultimodal result preview:")
display(multimodal_results_df)

print("\nOptional full-parser path:")
print("RUN_FULL_DOCUMENT_PARSE is currently:", RUN_FULL_DOCUMENT_PARSE)

async def optional_full_document_parse():
    if not RUN_FULL_DOCUMENT_PARSE:
        print(
            "Skipping parser-based PDF ingestion. "
            "Set RUN_FULL_DOCUMENT_PARSE=True near the top to test MinerU/Docling/PaddleOCR parsing."
        )
        return

    print("Starting full document parsing.")

    await rag.process_document_complete(
        file_path=str(report_pdf_path),
        output_dir=str(OUTPUT_DIR),
        parse_method=PARSE_METHOD,
        parser=PARSER_FOR_FULL_PARSE,
        display_stats=True,
        doc_id="parser-processed-synthetic-report",
    )

    answer = await safe_aquery(
        "After full parsing, what figures, tables, and equations are present in the report?",
        mode="hybrid",
        vlm_enhanced=False,
    )

    print(answer)

await optional_full_document_parse()

print("\n" + "=" * 80)
print("Tutorial complete.")
print("=" * 80)

print(f"Assets directory: {ASSET_DIR}")
print(f"RAG storage directory: {WORKING_DIR}")
print(f"Output directory: {OUTPUT_DIR}")

print("\nGenerated files:")
for path in sorted(ASSET_DIR.glob("*")):
    print(" -", path)

================================================================================
RAG-Anything Advanced Colab Tutorial
================================================================================

[1/10] Installing dependencies...

$ pip -q install -U "raganything[image,text]" "openai>=1.0.0" "python-dotenv" "reportlab" "pandas" "matplotlib" "tabulate"

$ pip -q install --no-cache-dir --force-reinstall "pillow==11.3.0"
Pillow version: 11.3.0

[2/10] Importing libraries...
Imports successful.

[3/10] Preparing directories and runtime settings...
Base directory: /content/raganything_advanced_tutorial
Assets directory: /content/raganything_advanced_tutorial/assets
Storage directory: /content/raganything_advanced_tutorial/rag_storage

[4/10] Entering OpenAI API key securely...
Paste your OpenAI API key here. Input is hidden: ··········
Captured key length: 164
Captured key prefix: sk-proj-Rm2X...
Captured key suffix: ...8AVOcA
Testing OpenAI chat API with the captured key...
Chat API test response: ok

Testing OpenAI embedding API...
Embedding vector length: 1536
OpenAI API key is working.
Chat model: gpt-4o-mini
Vision model: gpt-4o-mini
Embedding model: text-embedding-3-small
Embedding dimension: 1536

[5/10] Creating a synthetic multimodal report...
Created chart: /content/raganything_advanced_tutorial/assets/raganything_quality_trend.png
Created PDF: /content/raganything_advanced_tutorial/assets/synthetic_multimodal_rag_report.pdf

Synthetic table:

  Month  Query Volume  Hybrid Accuracy  Average Latency ms
0   Jan          1200             0.71                 980
1   Feb          1700             0.74                 920
2   Mar          2100             0.79                 850
3   Apr          2600             0.83                 790
4   May          3300             0.87                 760
5   Jun          4100             0.91                 730

INFO: RAGAnything initialized with config:
INFO:   Working directory: /content/raganything_advanced_tutorial/rag_storage
INFO:   Parser: mineru
INFO:   Parse method: auto
INFO:   Multimodal processing - Image: True, Table: True, Equation: True
INFO:   Max concurrent files: 1

[6/10] Building direct multimodal content_list...
Saved content list: /content/raganything_advanced_tutorial/assets/content_list.json

[7/10] Defining clean OpenAI model and embedding functions...
Model and embedding functions ready.

[8/10] Initializing RAG-Anything...
Working directory: /content/raganything_advanced_tutorial/rag_storage

[9/10] Inserting multimodal content and running retrieval queries...

INFO: Parser 'mineru' installation verified
INFO: Initializing LightRAG with parameters: {'working_dir': '/content/raganything_advanced_tutorial/rag_storage'}
INFO: [] Created new empty graph file: /content/raganything_advanced_tutorial/rag_storage/graph_chunk_entity_relation.graphml
INFO: Role LLM Configuration (initialized):
INFO:  - extract: None/None, host=None, max_async=4, timeout=240
INFO:  - keyword: None/None, host=None, max_async=4, timeout=240
INFO:  - query: None/None, host=None, max_async=4, timeout=240
INFO:  - vlm: None/None, host=None, max_async=4, timeout=240
INFO: [] Process 3576 KV load full_docs with 0 records
INFO: [] Process 3576 KV load text_chunks with 0 records
INFO: [] Process 3576 KV load full_entities with 0 records
INFO: [] Process 3576 KV load full_relations with 0 records
INFO: [] Process 3576 KV load entity_chunks with 0 records
INFO: [] Process 3576 KV load relation_chunks with 0 records
INFO: [] Process 3576 KV load llm_response_cache with 0 records
INFO: [] Process 3576 doc status load doc_status with 0 records
INFO: [] Process 3576 KV load parse_cache with 0 records
INFO: [] Process 3576 KV load multimodal_status with 0 records
INFO: Multimodal processors initialized with context support
INFO: Available processors: ['image', 'table', 'equation', 'generic']
INFO: Context configuration: ContextConfig(context_window=1, context_mode='page', max_context_tokens=2000, include_headers=True, include_captions=True, filter_content_types=['text'])
INFO: LightRAG, parse cache, multimodal status cache, and multimodal processors initialized
INFO: Starting direct content list insertion for: synthetic_multimodal_rag_report.pdf (5 items)
INFO:
Content Information:
INFO: * Total blocks in content_list: 5
INFO: * Content block types:
INFO:   - text: 2
INFO:   - table: 1
INFO:   - equation: 1
INFO:   - image: 1
INFO: Content separation complete:
INFO:   - Text content length: 707 characters
INFO:   - Multimodal items count: 3
INFO:   - Multimodal type distribution: {'table': 1, 'equation': 1, 'image': 1}
INFO: Setting content source for context-aware multimodal processing...
INFO: Content source set with format: minerU
INFO: Content source set with format: minerU
INFO: Content source set with format: minerU
INFO: Content source set with format: minerU
INFO: Content source set for context extraction (format: minerU)
INFO: Starting text content insertion into LightRAG...
INFO: Processing 1 document(s)
INFO: Parsing (native): synthetic-multimodal-rag-report
INFO: Extracting stage 1/1: synthetic_multimodal_rag_report.pdf
INFO: Processing d-id: synthetic-multimodal-rag-report
INFO: Chunking F(legacy): size=900, split_only=False, overlap=120, doc_id: synthetic-multimodal-rag-report
INFO: extract LLM func: 4 new workers initialized (Timeouts: Func: 240s, Worker: 480s, Health Check: 495s)
INFO:  == LLM cache == saving: default:extract:0b5973e86791e9dda5469ec00f3d31db
INFO:  == LLM cache == saving: default:extract:e08e7096f6833956b50bf11cfb9f47dc
INFO: Chunk 1 of 1 extracted 12 Ent + 11 Rel synthetic-multimodal-rag-report-chunk-000
INFO: Merging stage 1/1: synthetic_multimodal_rag_report.pdf
INFO: Phase 1: Processing 12 entities from synthetic-multimodal-rag-report (async: 8)
INFO: Phase 2: Processing 11 relations from synthetic-multimodal-rag-report (async: 8)
INFO: Upserting relation VDB: `Retrieval Augmented Generation System->Synthetic Report`
INFO: Upserting relation VDB: `Retrieval Augmented Generation System->Textual Explanations`
INFO: Upserting relation VDB: `Performance Table->Retrieval Augmented Generation System`
INFO: Upserting relation VDB: `Retrieval Augmented Generation System->Scoring Equation`
INFO: Upserting relation VDB: `Retrieval Augmented Generation System->Trend Figure`
INFO: Upserting relation VDB: `Hybrid Retrieval->Retrieval Augmented Generation System`
INFO: Upserting relation VDB: `Local Retrieval->Retrieval Augmented Generation System`
INFO: Upserting relation VDB: `Global Retrieval->Retrieval Augmented Generation System`
INFO: Upserting relation VDB: `Naive Retrieval->Retrieval Augmented Generation System`
INFO: Upserting relation VDB: `Hybrid Accuracy->Retrieval Augmented Generation System`
INFO: Upserting relation VDB: `Average Latency->Retrieval Augmented Generation System`
INFO: Phase 2 relation processing completed for synthetic-multimodal-rag-report: edges=11 added_entities=0
INFO: Phase 3: Updating final 12(12+0) entities and  11 relations from synthetic-multimodal-rag-report
INFO: Completed merging: 12 entities, 0 extra entities, 11 relations
INFO: [] entities flush: embedding 12 vectors in 2 batch(es) (batch_num=10)
INFO: [] relationships flush: embedding 11 vectors in 2 batch(es) (batch_num=10)
INFO: [] chunks flush: embedding 1 vectors in 1 batch(es) (batch_num=10)
INFO: Embedding func: 8 new workers initialized (Timeouts: Func: 30s, Worker: 60s, Health Check: 75s)
INFO: [] Writing graph with 12 nodes, 11 edges
INFO: In memory DB persist to disk
INFO: Completed processing file 1/1: synthetic_multimodal_rag_report.pdf
INFO: Enqueued document processing pipeline stopped
INFO: Text content insertion complete
INFO: Starting multimodal content processing...
INFO: Starting to process 3 multimodal content items
INFO: Multimodal chunk generation progress: 1/3 (33.3%)
INFO: Multimodal chunk generation progress: 2/3 (66.7%)
INFO: Multimodal chunk generation progress: 3/3 (100.0%)
INFO: Generated descriptions for 3/3 multimodal items using correct processors
INFO: [] entities flush: embedding 3 vectors in 1 batch(es) (batch_num=10)
ERROR: Error in multimodal processing: 'role_llm_funcs'
WARNING: Falling back to individual multimodal processing
INFO: Processing item 1/3: table content
ERROR: Error processing table content: 'role_llm_funcs'
ERROR: Error processing multimodal content: not enough values to unpack (expected 3, got 2)
INFO: Processing item 2/3: equation content
ERROR: Error processing equation content: 'role_llm_funcs'
ERROR: Error processing multimodal content: not enough values to unpack (expected 3, got 2)
INFO: Processing item 3/3: image content
ERROR: Error processing image content: 'role_llm_funcs'
ERROR: Error processing multimodal content: not enough values to unpack (expected 3, got 2)
INFO: Individual multimodal content processing complete
INFO: Content list insertion complete for: synthetic_multimodal_rag_report.pdf
INFO: Executing text query: What is the main purpose of the multimodal RAG report?...
INFO: Query mode: naive
INFO: Naive query: 1 chunks (chunk_top_k:20 cosine:0.2)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 1 chunks
INFO: query LLM func: 4 new workers initialized (Timeouts: Func: 240s, Worker: 480s, Health Check: 495s)

Insertion complete.

================================================================================
QUERY MODE: NAIVE
================================================================================

Question: What is the main purpose of the multimodal RAG report?

INFO:  == LLM cache == saving: naive:query:bc827c2a5587926132c4149e0a42ffeb
INFO: Text query completed
INFO: Executing text query: How did hybrid accuracy and latency change from January to June?...
INFO: Query mode: naive
INFO: Naive query: 1 chunks (chunk_top_k:20 cosine:0.2)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 1 chunks

Answer:
The main purpose of the multimodal Retrieval Augmented Generation (RAG) report is to evaluate a system that indexes various modalities of information in order to provide answers to questions. This system utilizes textual explanations, a structured performance table, a scoring equation, and trend figures to address queries that require evidence distributed across multiple document modalities rather than relying on a single plain text passage. The report highlights the effectiveness of hybrid retrieval methods for answering cross-modal questions, aiming to improve the accuracy and efficiency of information retrieval.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: How did hybrid accuracy and latency change from January to June?

INFO:  == LLM cache == saving: naive:query:31a61a56cdbebf62bf0223e80f74d3cd
INFO: Text query completed
INFO: Executing text query: Why is hybrid retrieval better than naive retrieval for this report?...
INFO: Query mode: naive

Answer:
From January to June, the hybrid accuracy of the multimodal retrieval augmented generation system improved from **0.71** to **0.91**. Concurrently, the average latency decreased from **980 milliseconds** to **730 milliseconds**. This indicates a significant enhancement in performance over that period, both in accuracy and efficiency.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: Why is hybrid retrieval better than naive retrieval for this report?

INFO: Naive query: 1 chunks (chunk_top_k:20 cosine:0.2)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 1 chunks
INFO:  == LLM cache == saving: naive:query:ad87b8ea71067623c8e64d7a0d9c5698
INFO: Text query completed
INFO: Executing text query: What does the weighted multimodal score equation mean?...
INFO: Query mode: naive

Answer:
Hybrid retrieval is regarded as superior to naive retrieval in the context of the report due to its enhanced performance in addressing cross-modal questions. The report highlights several key points that illustrate this advantage:

1. **Specialized Retrieval**: Hybrid retrieval combines local and global retrieval methods. Local retrieval is effective for entity-specific lookups, while global retrieval effectively addresses broader themes. This combination allows the system to leverage the strengths of both approaches.

2. **Improved Accuracy**: The report documents an increase in hybrid retrieval accuracy from 0.71 in January to 0.91 in June. This significant improvement signifies that hybrid retrieval methods are better at producing correct answers when evidence is drawn from various document modalities.

3. **Optimized Latency**: Additionally, hybrid retrieval demonstrates enhanced efficiency, with average latency decreasing from 980 milliseconds to 730 milliseconds. Lower latency indicates that hybrid retrieval not only improves accuracy but does so more swiftly than naive retrieval.

In contrast, naive retrieval lacks the multi-faceted approach that hybrid methods incorporate, making it less effective for complex queries that require information from different sources.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: What does the weighted multimodal score equation mean?

INFO: Naive query: 1 chunks (chunk_top_k:20 cosine:0.2)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 1 chunks
INFO:  == LLM cache == saving: naive:query:04cc3b58fb9c4cc9900c5993b26d7ae7
INFO: Text query completed
INFO: Executing text query: What is the main purpose of the multimodal RAG report?...
INFO: Query mode: local
INFO: keyword LLM func: 4 new workers initialized (Timeouts: Func: 240s, Worker: 480s, Health Check: 495s)

Answer:
I do not have enough information to answer your query regarding the weighted multimodal score equation. The provided context does not include specific details about its definition or explanation.
--------------------------------------------------------------------------------

================================================================================
QUERY MODE: LOCAL
================================================================================

Question: What is the main purpose of the multimodal RAG report?

INFO:  == LLM cache == saving: local:keywords:ddc8125d6a264a9daa3b315c98dcc97d
WARNING: low_level_keywords is empty
INFO: Query edges: multimodal RAG report, purpose (top_k:40, cosine:0.2)
INFO: Global query: 12 entites, 11 relations
INFO: Raw search results: 12 entities, 11 relations, 0 vector chunks
INFO: After truncation: 12 entities, 11 relations
INFO: Selecting 1 from 1 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 11 relations
INFO: Round-robin merged chunks: 1 -> 1 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 12 entities, 11 relations, 1 chunks
INFO: Final chunks S+F/O: E12/1
INFO:  == LLM cache == saving: local:query:8a1573488844d0db9353a76b47abb10f
INFO: Text query completed
INFO: Executing text query: How did hybrid accuracy and latency change from January to June?...
INFO: Query mode: local

Answer:
The main purpose of the multimodal Retrieval Augmented Generation (RAG) report is to evaluate a system designed to answer questions by indexing various document types and utilizing evidence from multiple modalities. Specifically, the report focuses on the ability of the system to handle questions where the necessary information is distributed across different types of documents rather than being contained in a single text passage.

The key highlights of the report include the preference for hybrid retrieval for addressing cross-modal questions, the usefulness of local retrieval for specific entity lookups, the broader applicability of global retrieval for overarching themes, and the role of naive retrieval as a baseline comparison. Additionally, the report presents findings on hybrid accuracy improvements and a reduction in average latency times, which demonstrate the system's enhanced performance over time.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: How did hybrid accuracy and latency change from January to June?

INFO:  == LLM cache == saving: local:keywords:948b20e893012bc375b7bcacece7120a
WARNING: low_level_keywords is empty
INFO: Query edges: hybrid accuracy, latency, change, January to June (top_k:40, cosine:0.2)
INFO: Global query: 9 entites, 8 relations
INFO: Raw search results: 9 entities, 8 relations, 0 vector chunks
INFO: After truncation: 9 entities, 8 relations
INFO: Selecting 1 from 1 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 8 relations
INFO: Round-robin merged chunks: 1 -> 1 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 9 entities, 8 relations, 1 chunks
INFO: Final chunks S+F/O: E9/1
INFO:  == LLM cache == saving: local:query:db22d8da51fd888ed6a0ab9e49c2d88e
INFO: Text query completed
INFO: Executing text query: Why is hybrid retrieval better than naive retrieval for this report?...
INFO: Query mode: local

Answer:
From January to June, there was a notable improvement in both hybrid accuracy and latency for the retrieval augmented generation system.

- **Hybrid Accuracy**: It increased from **0.71 in January to 0.91 in June**, indicating a significant enhancement in performance over this period.

- **Average Latency**: The average time taken to retrieve information decreased from **980 milliseconds to 730 milliseconds**, reflecting improved efficiency in the system's operation.

These changes showcase the advancements made in the multimodal retrieval processes of the system during the first half of the year.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: Why is hybrid retrieval better than naive retrieval for this report?

INFO:  == LLM cache == saving: local:keywords:fd24aa921621018b840978badcfbb388
WARNING: low_level_keywords is empty
INFO: Query edges: hybrid retrieval, naive retrieval, report (top_k:40, cosine:0.2)
INFO: Global query: 12 entites, 11 relations
INFO: Raw search results: 12 entities, 11 relations, 0 vector chunks
INFO: After truncation: 12 entities, 11 relations
INFO: Selecting 1 from 1 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 11 relations
INFO: Round-robin merged chunks: 1 -> 1 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 12 entities, 11 relations, 1 chunks
INFO: Final chunks S+F/O: E12/1
INFO:  == LLM cache == saving: local:query:f5b791ce8b886d537a65351b74f80caa
INFO: Text query completed
INFO: Executing text query: What does the weighted multimodal score equation mean?...
INFO: Query mode: local

Answer:
Hybrid retrieval is considered better than naive retrieval for several reasons outlined in the synthetic report. Here are the key points:

1. **Preference for Cross-Modal Questions**: The hybrid retrieval method excels in addressing cross-modal questions where information might be distributed across various document types. This capability makes it more effective for answering complex queries that require integrating data from multiple sources.

2. **Flexible Retrieval Approaches**: Unlike naive retrieval, which is a simpler baseline that does not integrate different retrieval modalities, hybrid retrieval combines the strengths of local, global, and naive retrieval methods. This multifaceted approach allows for more targeted and comprehensive responses.

3. **Improved Performance Metrics**: The report highlights substantial improvements in hybrid accuracy over time, with a rise from 0.71 in January to 0.91 in June. This significant increase indicates that hybrid retrieval is more adept at delivering accurate results compared to naive retrieval, which does not show such versatility.

4. **Operational Efficiency**: The report mentions a reduction in average latency from 980 milliseconds to 730 milliseconds with hybrid retrieval, indicating that this method is not only more effective but also more efficient in terms of response time when compared to naive retrieval.

These factors collectively establish hybrid retrieval as the preferred method for enhancing the effectiveness and efficiency of the retrieval augmented generation system discussed in the report.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: What does the weighted multimodal score equation mean?

INFO:  == LLM cache == saving: local:keywords:0defdd89086a01582edee7857eaa7f7d
INFO: Query nodes: weighted multimodal score, equation (top_k:40, cosine:0.2)
INFO: Local query: 11 entites, 11 relations
INFO: Raw search results: 11 entities, 11 relations, 0 vector chunks
INFO: After truncation: 11 entities, 11 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 11 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 11 entities, 11 relations, 4 chunks
INFO: Final chunks S+F/O: E1/1 E8/2 E1/3 E1/4
INFO:  == LLM cache == saving: local:query:79779f94983d7e16fc467fab4fdc1b6b
INFO: Text query completed
INFO: Executing text query: What is the main purpose of the multimodal RAG report?...
INFO: Query mode: global

Answer:
The **Weighted Multimodal Retrieval Score** equation is a significant mathematical formulation used to assess the effectiveness of a multimodal retrieval system. This equation integrates scores from different data modalities, namely text, graph, and visual information, into a single composite metric.

Here's a breakdown of its components:

1. **Weights**:
   - The equation utilizes three weights: **alpha (α)** for text similarity, **beta (β)** for graph relationship similarity, and **gamma (γ)** for visual similarity. These weights control how much influence each modality has on the overall retrieval score.

2. **Purpose**:
   - By balancing the contributions of each modality based on their relevance to the specific query, the equation allows systems to adapt their responses to handle complex queries that span various types of data.

3. **Application**:
   - This equation is primarily applied in the field of artificial intelligence and information retrieval, particularly for systems designed to manage **multimodal data**. It helps in developing improved response systems that provide faster and more relevant answers to user queries.

4. **Importance**:
   - The weighted score is crucial for evaluation, providing quantifiable metrics for assessing retrieval accuracy. This can be validated by tracking performance trends over time, correlating improvements in system latency with the effectiveness of the retrieval approach.

Overall, the Weighted Multimodal Retrieval Score serves to optimize retrieval processes for enhanced performance across multiple information sources, ultimately improving user experiences.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

================================================================================
QUERY MODE: GLOBAL
================================================================================

Question: What is the main purpose of the multimodal RAG report?

INFO:  == LLM cache == saving: global:keywords:4007d163085b858e7ba48d7441627244
INFO: Query edges: multimodal RAG report, purpose (top_k:40, cosine:0.2)
INFO: Global query: 12 entites, 11 relations
INFO: Raw search results: 12 entities, 11 relations, 0 vector chunks
INFO: After truncation: 12 entities, 11 relations
INFO: Selecting 1 from 1 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 11 relations
INFO: Round-robin merged chunks: 1 -> 1 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 12 entities, 11 relations, 1 chunks
INFO: Final chunks S+F/O: E12/1
INFO:  == LLM cache == saving: global:query:a5bf132bd0ff77ec6bf4093e4d448523
INFO: Text query completed
INFO: Executing text query: How did hybrid accuracy and latency change from January to June?...
INFO: Query mode: global

Answer:
The main purpose of the multimodal Retrieval Augmented Generation (RAG) report is to evaluate a system designed to answer questions whose evidence is distributed across multiple document modalities. This system indexes various components such as textual explanations, a structured performance table, a scoring equation, and a trend figure. The report emphasizes the effectiveness of the hybrid retrieval method for cross-modal questions, while also noting the utility of local retrieval for entity-specific lookups and global retrieval for broader themes.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: How did hybrid accuracy and latency change from January to June?

INFO:  == LLM cache == saving: global:keywords:f792607837646d5bb3e2210ed5a2ff04
INFO: Query edges: hybrid accuracy, latency, time period (top_k:40, cosine:0.2)
INFO: Global query: 11 entites, 10 relations
INFO: Raw search results: 11 entities, 10 relations, 0 vector chunks
INFO: After truncation: 11 entities, 10 relations
INFO: Selecting 1 from 1 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 10 relations
INFO: Round-robin merged chunks: 1 -> 1 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 11 entities, 10 relations, 1 chunks
INFO: Final chunks S+F/O: E11/1
INFO:  == LLM cache == saving: global:query:175977b5489c545329ce7ec564bdbde2
INFO: Text query completed
INFO: Executing text query: Why is hybrid retrieval better than naive retrieval for this report?...
INFO: Query mode: global

Answer:
From January to June, there were notable improvements in both hybrid accuracy and latency for the Retrieval Augmented Generation System:

- **Hybrid Accuracy**: The hybrid accuracy metric rose significantly, increasing from **0.71 in January** to **0.91 in June**. This demonstrates a marked improvement in the performance of the system over this period.

- **Average Latency**: The average latency decreased substantially, going from **980 milliseconds** in January down to **730 milliseconds** in June. This reduction indicates that the retrieval process became faster during the same timeframe.

These changes reflect the system's enhanced efficiency and effectiveness in retrieving information across different modalities.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: Why is hybrid retrieval better than naive retrieval for this report?

INFO:  == LLM cache == saving: global:keywords:34cd3522cf8bcad21cfaa3c6a53a6fb6
INFO: Query edges: hybrid retrieval, naive retrieval, report (top_k:40, cosine:0.2)
INFO: Global query: 12 entites, 11 relations
INFO: Raw search results: 12 entities, 11 relations, 0 vector chunks
INFO: After truncation: 12 entities, 11 relations
INFO: Selecting 1 from 1 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 11 relations
INFO: Round-robin merged chunks: 1 -> 1 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 12 entities, 11 relations, 1 chunks
INFO: Final chunks S+F/O: E12/1
INFO:  == LLM cache == saving: global:query:f3bcf6ae12184552023bb4b8152c2fef
INFO: Text query completed
INFO: Executing text query: What does the weighted multimodal score equation mean?...
INFO: Query mode: global

Answer:
Hybrid retrieval is considered better than naive retrieval in the context of the report due to several key factors:

1. **Cross-Modal Question Handling**: The report indicates that hybrid retrieval is preferred specifically for addressing cross-modal questions, where evidence is distributed across various document modalities. This capability allows it to effectively manage and integrate different types of data sources to provide comprehensive answers.

2. **Performance Improvement**: The report documents a significant improvement in hybrid accuracy, increasing from 0.71 in January to 0.91 in June. This improvement reflects the effectiveness of hybrid retrieval in processing and retrieving relevant information more accurately over time compared to naive retrieval, which serves only as a simpler baseline.

3. **Diverse Retrieval Approaches**: Hybrid retrieval encompasses both local and global retrieval methods, providing flexibility in how queries are handled. Local retrieval focuses on specific entity lookups, while global retrieval addresses broader themes, allowing for a more holistic approach to information retrieval, which naive retrieval lacks.

In summary, hybrid retrieval's ability to manage multi-faceted queries and its proven enhancement in accuracy make it superior to naive retrieval as per the findings of the synthetic report.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: What does the weighted multimodal score equation mean?

INFO:  == LLM cache == saving: global:keywords:da85ea6165bd3ae893f919f734a174ae
INFO: Query edges: weighted multimodal score, equation meaning (top_k:40, cosine:0.2)
INFO: Global query: 10 entites, 9 relations
INFO: Raw search results: 10 entities, 9 relations, 0 vector chunks
INFO: After truncation: 10 entities, 9 relations
INFO: Selecting 1 from 1 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 9 relations
INFO: Round-robin merged chunks: 1 -> 1 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 10 entities, 9 relations, 1 chunks
INFO: Final chunks S+F/O: E10/1
INFO:  == LLM cache == saving: global:query:22ec6961016a2f7342074e9b4f388e98
INFO: Text query completed
INFO: Executing text query: What is the main purpose of the multimodal RAG report?...
INFO: Query mode: hybrid

Answer:
I do not have enough information to answer your question about the weighted multimodal score equation.
--------------------------------------------------------------------------------

================================================================================
QUERY MODE: HYBRID
================================================================================

Question: What is the main purpose of the multimodal RAG report?

INFO:  == LLM cache == saving: hybrid:keywords:07f7a0c3ec038d97e3f59aa66a73185f
WARNING: low_level_keywords is empty
INFO: Query edges: multimodal RAG report, purpose (top_k:40, cosine:0.2)
INFO: Global query: 12 entites, 11 relations
INFO: Raw search results: 12 entities, 11 relations, 0 vector chunks
INFO: After truncation: 12 entities, 11 relations
INFO: Selecting 1 from 1 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 11 relations
INFO: Round-robin merged chunks: 1 -> 1 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 12 entities, 11 relations, 1 chunks
INFO: Final chunks S+F/O: E12/1
INFO:  == LLM cache == saving: hybrid:query:b5ee6e59a3efeff4bfe6f70cb51fee16
INFO: Text query completed
INFO: Executing text query: How did hybrid accuracy and latency change from January to June?...
INFO: Query mode: hybrid

Answer:
The main purpose of the multimodal Retrieval Augmented Generation (RAG) report is to evaluate a system that indexes various document types to answer questions based on evidence distributed across multiple modalities. The report emphasizes the system's goal of effectively addressing questions that require information from diverse sources rather than relying solely on a single plain text passage.

Additionally, the report highlights the preference for hybrid retrieval in dealing with cross-modal questions, and also discusses other retrieval methods like local and global retrieval, as well as naive retrieval as a baseline comparison.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: How did hybrid accuracy and latency change from January to June?

INFO:  == LLM cache == saving: hybrid:keywords:cc0f56079726cdfcaac6c76566fce290
WARNING: low_level_keywords is empty
INFO: Query edges: hybrid accuracy, latency, change, January to June (top_k:40, cosine:0.2)
INFO: Global query: 9 entites, 8 relations
INFO: Raw search results: 9 entities, 8 relations, 0 vector chunks
INFO: After truncation: 9 entities, 8 relations
INFO: Selecting 1 from 1 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 8 relations
INFO: Round-robin merged chunks: 1 -> 1 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 9 entities, 8 relations, 1 chunks
INFO: Final chunks S+F/O: E9/1
INFO:  == LLM cache == saving: hybrid:query:3cb81f439e719905d40e37b3af47b966
INFO: Text query completed
INFO: Executing text query: Why is hybrid retrieval better than naive retrieval for this report?...
INFO: Query mode: hybrid

Answer:
From January to June, the **Hybrid Accuracy** of the Retrieval Augmented Generation System improved significantly, rising from **0.71** to **0.91**. Simultaneously, the **Average Latency** decreased, falling from **980 milliseconds** to **730 milliseconds**. This change indicates both an increase in performance accuracy and a reduction in the time taken to retrieve information over this period.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: Why is hybrid retrieval better than naive retrieval for this report?

INFO:  == LLM cache == saving: hybrid:keywords:f53e97d034e30e4df8abb8d57d85fe08
WARNING: low_level_keywords is empty
INFO: Query edges: hybrid retrieval, naive retrieval, report (top_k:40, cosine:0.2)
INFO: Global query: 12 entites, 11 relations
INFO: Raw search results: 12 entities, 11 relations, 0 vector chunks
INFO: After truncation: 12 entities, 11 relations
INFO: Selecting 1 from 1 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 11 relations
INFO: Round-robin merged chunks: 1 -> 1 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 12 entities, 11 relations, 1 chunks
INFO: Final chunks S+F/O: E12/1
INFO:  == LLM cache == saving: hybrid:query:7e2f03ce2e6f0f64b1a7b9cfca127262
INFO: Text query completed
INFO: Executing text query: What does the weighted multimodal score equation mean?...
INFO: Query mode: hybrid

Answer:
Hybrid retrieval is considered better than naive retrieval in the context of the evaluated multimodal retrieval augmented generation system due to several key factors:

1. **Cross-Modal Effectiveness**: Hybrid retrieval is specifically preferred for addressing cross-modal questions. This ability allows the system to effectively retrieve information from multiple types of documents or modalities, which is critical when the evidence for a question is not confined to a single text passage.

2. **Performance Improvement**: According to the synthetic report, the hybrid accuracy of the retrieval system shows significant improvement, rising from 0.71 in January to 0.91 in June. This indicates a noticeable enhancement in the retrieval capabilities when using hybrid methods compared to the baseline performance offered by naive retrieval.

3. **Specificity and Breadth**: While naive retrieval serves as a simpler baseline method, it lacks the nuanced capabilities of hybrid retrieval, which utilizes local and global retrieval techniques. Local retrieval is ideal for entity-specific lookups, while global retrieval effectively addresses broader themes, making hybrid retrieval a more versatile choice.

These attributes collectively underscore why hybrid retrieval is deemed superior to naive retrieval within the context of the report's findings.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: What does the weighted multimodal score equation mean?

INFO:  == LLM cache == saving: hybrid:keywords:435fbf1282b07ee9b00a33d4f28f4872
INFO: Query nodes: weighted, multimodal, score, equation (top_k:40, cosine:0.2)
INFO: Local query: 12 entites, 11 relations
INFO: Query edges: weighted multimodal score, equation, mean (top_k:40, cosine:0.2)
INFO: Global query: 9 entites, 8 relations
INFO: Raw search results: 13 entities, 11 relations, 0 vector chunks
INFO: After truncation: 13 entities, 11 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 11 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 13 entities, 11 relations, 4 chunks
INFO: Final chunks S+F/O: E1/1 E10/2 E1/3 E1/4
INFO:  == LLM cache == saving: hybrid:query:6a5bafea83751d5a1b4905cfe72b4863
INFO: Text query completed

Answer:
The **Weighted Multimodal Retrieval Score** equation is a mathematical construct used to evaluate the effectiveness of a multimodal retrieval system that integrates various information sources, such as text, graphs, and visual data. Here’s a breakdown of its components and significance:

### Components of the Equation
- **Alpha (α)**: This weight controls the similarity contribution from textual data.
- **Beta (β)**: This weight governs the effect of graph relationship similarities.
- **Gamma (γ)**: This parameter adjusts the influence of visual data on the overall score.

### Purpose and Application
- The equation enables the system to provide adaptive responses by quantifying how different modalities contribute to answering complex queries.
- By assigning different weights to the various types of data, the equation allows the retrieval system to dynamically balance the contributions based on relevance, ultimately leading to improved retrieval accuracy.

### Importance
- This score is pivotal in the field of artificial intelligence and information retrieval, as it provides a measurable method to assess the system's performance.
- The weighted approach aligns with optimization principles, aiming to maximize retrieval effectiveness across multiple data types, thereby enhancing the user experience with timely and relevant information retrieval.

In summary, the weighted multimodal retrieval score equation acts as a composite metric that effectively evaluates how well a retrieval system manages and integrates diverse modalities of information to respond to user queries.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Query result preview:

,mode,question,answer_preview
0,naive,What is the main purpose of the multimodal RAG...,The main purpose of the multimodal Retrieval A...
1,naive,How did hybrid accuracy and latency change fro...,"From January to June, the hybrid accuracy of t..."
2,naive,Why is hybrid retrieval better than naive retr...,Hybrid retrieval is regarded as superior to na...
3,naive,What does the weighted multimodal score equati...,I do not have enough information to answer you...
4,local,What is the main purpose of the multimodal RAG...,The main purpose of the multimodal Retrieval A...
5,local,How did hybrid accuracy and latency change fro...,"From January to June, there was a notable impr..."
6,local,Why is hybrid retrieval better than naive retr...,Hybrid retrieval is considered better than nai...
7,local,What does the weighted multimodal score equati...,The **Weighted Multimodal Retrieval Score** eq...
8,global,What is the main purpose of the multimodal RAG...,The main purpose of the multimodal Retrieval A...
9,global,How did hybrid accuracy and latency change fro...,"From January to June, there were notable impro..."
10,global,Why is hybrid retrieval better than naive retr...,Hybrid retrieval is considered better than nai...
11,global,What does the weighted multimodal score equati...,I do not have enough information to answer you...
12,hybrid,What is the main purpose of the multimodal RAG...,The main purpose of the multimodal Retrieval A...
13,hybrid,How did hybrid accuracy and latency change fro...,"From January to June, the **Hybrid Accuracy** ..."
14,hybrid,Why is hybrid retrieval better than naive retr...,Hybrid retrieval is considered better than nai...
15,hybrid,What does the weighted multimodal score equati...,The **Weighted Multimodal Retrieval Score** eq...

INFO: Executing multimodal query: Using the supplied table, identify the month with the highest hybrid accuracy, the month with the lo...
INFO: Query mode: hybrid
INFO: Starting multimodal query content processing...
INFO: Processing 1/1 multimodal content: table

[10/10] Running explicit multimodal queries...

================================================================================
Table-aware query
================================================================================
Question: Using the supplied table, identify the month with the highest hybrid accuracy, the month with the lowest latency, and explain whether the trend supports the report conclusion.

INFO: Multimodal query content processing completed
INFO: Generated enhanced query length: 2363 characters
INFO: Executing VLM enhanced query: User query: Using the supplied table, identify the month with the highest hybrid accuracy, the month...
INFO:  == LLM cache == saving: hybrid:keywords:e6e36d0ab5473f7c455aab5ffd98d70a
INFO: Query nodes: January, February, March, April, May, June, 0.71, 0.91, 980 ms, 730 ms, query processing (top_k:40, cosine:0.2)
INFO: Local query: 10 entites, 7 relations
INFO: Query edges: performance analysis, system metrics, hybrid accuracy, average latency, query volume, trend analysis (top_k:40, cosine:0.2)
INFO: Global query: 10 entites, 9 relations
INFO: Raw search results: 14 entities, 10 relations, 0 vector chunks
INFO: After truncation: 14 entities, 10 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 10 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 14 entities, 10 relations, 4 chunks
INFO: Final chunks S+F/O: E1/1 E1/2 E11/3 E1/4
INFO: Found 1 image path matches in prompt
INFO: Processed 1 images for VLM
INFO: VLM enhanced query completed
INFO: Saved multimodal query result to cache: multimodal_query...
INFO: Multimodal query completed
INFO: Executing multimodal query: Explain how this scoring equation should affect retrieval when the user's question needs textual, gr...
INFO: Query mode: hybrid
INFO: Starting multimodal query content processing...
INFO: Processing 1/1 multimodal content: equation

Answer:
To address your query regarding the performance analysis of the system from January to June, let's extract and summarize the relevant insights based on the provided table and its findings.

### Hybrid Accuracy and Latency Analysis

1. **Month with Highest Hybrid Accuracy**:
   - The month with the highest hybrid accuracy is **June**, where the hybrid accuracy reached **0.91**.

2. **Month with Lowest Latency**:
   - The month with the lowest latency is also **June**, recording an average latency of **730 milliseconds**.

### Trend Analysis Supporting the Report Conclusion

The trends observed in the data support the conclusions drawn in the report regarding the performance and effectiveness of the multimodal retrieval augmented generation system:

- **Consistent Improvement**: The hybrid accuracy shows a clear upward trend from **0.71 in January** to **0.91 in June**. This increase signifies enhancements in the system's accuracy in retrieving answers correctly as user demand grows.

- **Decreasing Latency**: The average latency steadily decreases from **980 milliseconds in January** to **730 milliseconds in June**. This reduction indicates enhanced speed and efficiency in processing queries, essential for a system that is expected to handle increasing query volumes.

- **Positive Correlation**: There is a notable positive correlation between growing query volume and improvements in both hybrid accuracy and latency. As the system receives **increasing queries**—from **1200 in January** to **4100 in June**—it not only becomes more adept at answering questions accurately but also processes them more swiftly. This relationship underlines the effectiveness of continuous optimization efforts.

### Conclusion

Overall, the performance metrics reflected in the table corroborate the report's conclusions, indicating that improvements in hybrid accuracy and reductions in latency have been achieved in tandem with increased usage. This highlights the system's development and efficiency in answering cross-modal questions, reinforcing the appropriateness of the hybrid retrieval approach.

### References

- [1] synthetic_multimodal_rag_report.pdf

================================================================================
Equation-aware query
================================================================================
Question: Explain how this scoring equation should affect retrieval when the user's question needs textual, graph, and visual evidence at the same time.

INFO: Multimodal query content processing completed
INFO: Generated enhanced query length: 3669 characters
INFO: Executing VLM enhanced query: User query: Explain how this scoring equation should affect retrieval when the user's question needs...
INFO:  == LLM cache == saving: hybrid:keywords:251ef092974275ef948ab291f5638427
INFO: Query nodes: Weighted Multimodal Retrieval Score, text, graphs, visual content, Score(q,d), Sim_text(q,d), Sim_graph(q,d), Sim_visual(q,d), TF-IDF, cosine similarity, weights, recommendation systems, search engines, data retrieval, AI (top_k:40, cosine:0.2)
INFO: Local query: 15 entites, 11 relations
INFO: Query edges: multimodal retrieval, information retrieval, scoring equation, user queries (top_k:40, cosine:0.2)
INFO: Global query: 12 entites, 11 relations
INFO: Raw search results: 15 entities, 11 relations, 0 vector chunks
INFO: After truncation: 15 entities, 11 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 11 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 15 entities, 11 relations, 4 chunks
INFO: Final chunks S+F/O: E1/1 E12/2 E1/3 E1/4
INFO: Found 1 image path matches in prompt
INFO: Processed 1 images for VLM
INFO: VLM enhanced query completed
INFO: Saved multimodal query result to cache: multimodal_query...
INFO: Multimodal query completed
INFO: Executing multimodal query: Connect the table, equation, and document conclusion into one explanation of why a multimodal hybrid...
INFO: Query mode: hybrid
INFO: Starting multimodal query content processing...
INFO: Processing 1/2 multimodal content: table

Answer:
The **Weighted Multimodal Retrieval Score** equation is pivotal in enhancing the performance of information retrieval systems, especially when queries necessitate textual, graph, and visual evidence simultaneously. This scoring system is designed to evaluate how well a document corresponds to a user's query by integrating multiple types of data inputs.

### Components of the Scoring Equation

1. **Overall Score**:
   - The score \(Score(q,d)\) quantifies the relevance of a document \(d\) in response to a specific query \(q\). This score is derived from the weighted combination of evaluations from various modalities.

2. **Text Similarity \(Sim_{text}(q,d)\)**:
   - This component measures the textual similarity between the query and the document. It employs techniques like term frequency-inverse document frequency (TF-IDF) and cosine similarity to assess how closely related the document's text is to the user's query.

3. **Graph Similarity \(Sim_{graph}(q,d)\)**:
   - This term considers graph-based data connections, useful when information is structured as nodes and edges (e.g., knowledge graphs). It evaluates how well the document aligns with the query's requirements from a relational perspective.

4. **Visual Similarity \(Sim_{visual}(q,d)\)**:
   - This aspect captures the relevance of visual elements in the user's query when compared to any associated images or videos in the documents, ensuring a multi-dimensional assessment of relevance.

5. **Weights**:
   - The coefficients \(\alpha\), \(\beta\), and \(\gamma\) modulate the influence of each modality. By adjusting these weights, the system can be tailored to prioritize certain data types based on specific contexts or user needs.

### Impact on Retrieval

- **Enhanced Relevance**: The equation allows the retrieval system to provide more pertinent results by acknowledging and synthesizing different forms of evidence. When a query requires insights drawn from text, graphs, and visuals, the scoring system ensures that documents meeting those multi-modal criteria rank higher.

- **Flexible Response Adaptation**: By modifying the weights assigned to each type of evidence, the retrieval system can adapt to varying scenarios. For instance, if a visual component is deemed critical for a specific query type, the weight for \(Sim_{visual}\) can be increased, thereby amplifying the system’s ability to produce visually relevant results.

- **Comprehensive Understanding of Queries**: The multi-faceted approach facilitated by this scoring equation aligns well with complex user inquiries where a single mode of evidence is inadequate. It integrates textual explanations, relational data, and visual context, ensuring a holistic retrieval process that enhances the quality of answers provided.

### Real-World Applications

The application of the Weighted Multimodal Retrieval Score can be seen in various domains:

- **Search Engines**: These systems benefit from ranking results that encompass diverse data forms, ensuring users receive comprehensive answers.
- **Recommendation Systems**: Here, the equation balances textual reviews with visual content, optimizing content suggestions based on user preferences.
- **Data Retrieval in AI**: In environments rich with heterogeneous data types, such as academic literature or social networks, this equation significantly improves the relevancy of results retrieved.

### Conclusion

In summary, the Weighted Multimodal Retrieval Score is crucial for modern retrieval systems. By effectively integrating textual, graph, and visual inputs, it provides a robust framework that enhances response relevance, adaptability, and comprehensiveness, catering to the multifaceted nature of user queries.

### References

* [1] synthetic_multimodal_rag_report.pdf

================================================================================
Combined multimodal query
================================================================================
Question: Connect the table, equation, and document conclusion into one explanation of why a multimodal hybrid retriever is useful.

INFO: Processing 2/2 multimodal content: equation
INFO: Multimodal query content processing completed
INFO: Generated enhanced query length: 5412 characters
INFO: Executing VLM enhanced query: User query: Connect the table, equation, and document conclusion into one explanation of why a multi...
INFO:  == LLM cache == saving: hybrid:keywords:2c9a85aa1cf56806c481d5b8a661d8b6
INFO: Query nodes: equation, monthly performance data, query volume, hybrid accuracy, average latency, retrieval score, textual data, graphical representations, visual content, search engines, multimedia retrieval systems, user experience (top_k:40, cosine:0.2)
INFO: Local query: 15 entites, 11 relations
INFO: Query edges: multimodal hybrid retriever, explanation, query performance, information retrieval (top_k:40, cosine:0.2)
INFO: Global query: 12 entites, 11 relations
INFO: Raw search results: 15 entities, 11 relations, 0 vector chunks
INFO: After truncation: 15 entities, 11 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 11 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 15 entities, 11 relations, 4 chunks
INFO: Final chunks S+F/O: E1/1 E1/2 E12/3 E1/4
INFO: Found 1 image path matches in prompt
INFO: Processed 1 images for VLM
INFO: VLM enhanced query completed
INFO: Saved multimodal query result to cache: multimodal_query...
INFO: Multimodal query completed

Answer:
A multimodal hybrid retriever leverages the integration of various data types to enhance query processing capabilities, as demonstrated by the performance metrics, the weighted multimodal retrieval score, and the conclusions drawn in the document.

### Connection Between the Table and Hybrid Retriever Effectiveness

The performance table summarizes key metrics from January to June 2023, detailing trends in **query volume**, **hybrid accuracy**, and **average latency**.

- **Query Volume**: This metric shows an increase from 1,200 queries in January to 4,100 in June, indicating a growing demand for the hybrid retrieval system.
- **Hybrid Accuracy**: The accuracy of the system improves from 0.71 to 0.91 during the same period, signifying enhanced capability to answer diverse, cross-modal questions effectively.
- **Average Latency**: This metric decreases from 980 ms to 730 ms, showcasing improved system efficiency and responsiveness, which is crucial for user satisfaction.

### Role of the Weighted Multimodal Retrieval Score

The weighted multimodal retrieval score highlighted in the equation serves to quantitatively assess the performance of the retrieval system by combining multiple types of data (textual, graphical, visual):

\[
\text{Score}(q,d) = \alpha \cdot Sim_{\text{text}}(q,d) + \beta \cdot Sim_{\text{graph}}(q,d) + \gamma \cdot Sim_{\text{visual}}(q,d)
\]

- **Sim_{\text{text}}** assesses textual alignment between the query and document.
- **Sim_{\text{graph}}** evaluates graphical relationships.
- **Sim_{\text{visual}}** measures visual content relevance.

The weights (α, β, γ) can be adjusted based on query context to optimize results, ensuring that users receive comprehensive and relevant information from multiple modalities.

### Conclusion from the Document

The findings in the document support these metrics by concluding that hybrid retrieval is particularly effective for answering cross-modal questions. It notes that local retrieval is suited for specific entity lookups, while global retrieval captures broader themes. The improvements in hybrid accuracy from 0.71 to 0.91 and reductions in latency from 980 ms to 730 ms underscore the operational effectiveness of the system as usage grows.

### Summary of Benefits

Integrating these elements illustrates the utility of a multimodal hybrid retriever:

- **Improved Retrieval Quality**: The combination of different data types enhances the relevance of the results presented to users, contributing to higher satisfaction and engagement.
- **Adaptability**: By customizing the influence of various data types based on user needs, the system can respond better to a wide range of queries.
- **User Experience**: Faster response times coupled with higher accuracy ensure a positive interaction, critical in today’s data-driven environments.

Overall, the multimodal hybrid retriever demonstrates a well-rounded approach in improving retrieval capabilities, making it an essential tool for effective information processing across diverse datasets.

### References

- [1] synthetic_multimodal_rag_report.pdf

Multimodal result preview:

,case,question,answer_preview
0,Table-aware query,"Using the supplied table, identify the month w...",To address your query regarding the performanc...
1,Equation-aware query,Explain how this scoring equation should affec...,The **Weighted Multimodal Retrieval Score** eq...
2,Combined multimodal query,"Connect the table, equation, and document conc...",A multimodal hybrid retriever leverages the in...

Optional full-parser path:
RUN_FULL_DOCUMENT_PARSE is currently: False
Skipping parser-based PDF ingestion. Set RUN_FULL_DOCUMENT_PARSE=True near the top to test MinerU/Docling/PaddleOCR parsing.

================================================================================
Tutorial complete.
================================================================================
Assets directory: /content/raganything_advanced_tutorial/assets
RAG storage directory: /content/raganything_advanced_tutorial/rag_storage
Output directory: /content/raganything_advanced_tutorial/output

Generated files:
 - /content/raganything_advanced_tutorial/assets/content_list.json
 - /content/raganything_advanced_tutorial/assets/raganything_quality_trend.png
 - /content/raganything_advanced_tutorial/assets/synthetic_multimodal_rag_report.pdf